version: '3'
services:
  db:
    image: postgres
    networks:
      - bear-rx-norm
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/drug-library
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - bear-rx-norm
networks:
  bear-rx-norm:
